# Cargo.toml (root)
[workspace]
members = [
    "crates/stbl_core",
    "crates/stbl_cache",
    "crates/stbl_cli",
    "crates/stbl_embedded_assets",
]
resolver = "2"

#
# [package]
# name = "stbl"
# version = "0.1.0"
# edition = "2024"
#
# [dependencies]
#
